version: '2.1'
services:

  config:
    build: config
    ports:
      - $CONFIG_SERVICE_DEV_PORT:$CONFIG_SERVICE_DEV_PORT

  gateway-point:
    build: gateway-point

  auth-service:
    build: auth-service
    ports:
      - $AUTH_SERVICE_DEV_PORT:$AUTH_SERVICE_DEV_PORT

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build: account-service
    ports:
      - $ACCOUNT_SERVICE_DEV_PORT:$ACCOUNT_SERVICE_DEV_PORT

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  registry:
    build: registry