security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:${AUTH_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: mservicet
      port: ${MONGODB_SERVICE_INTERNAL_DEV_PORT}

server:
  servlet:
    context-path: /accounts
  port: ${ACCOUNT_SERVICE_DEV_PORT}