security:
  oauth2:
    client:
      clientId: device-service
      clientSecret: ${DEVICE_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:${DEVICE_SERVICE_DEV_PORT}/mservicet/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: device-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: mservicet
      port: ${MONGODB_SERVICE_INTERNAL_DEV_PORT}

server:
  servlet:
    context-path: /devices
  port: ${DEVICE_SERVICE_DEV_PORT}